# Generated by Django 4.2.23 on 2025-07-11 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookapi', '0003_adminactivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminactivitylog',
            name='related_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_logs', to='bookapi.book'),
        ),
        migrations.AddField(
            model_name='adminactivitylog',
            name='related_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_actions', to=settings.AUTH_USER_MODEL),
        ),
    ]
