# Generated by Django 4.2.23 on 2025-06-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Sci-Fi', 'Science Fiction'), ('Mystery', 'Mystery'), ('Romance', 'Romance'), ('Biography', 'Biography')], max_length=50),
        ),
    ]
