# Generated by Django 4.2.23 on 2025-06-27 06:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_borrower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='borrow_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
