# Generated by Django 4.2.23 on 2025-07-03 08:00

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_downloadlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfbook',
            name='pdf_file',
            field=models.FileField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='pdfs/'),
        ),
    ]
