# Generated by Django 4.2.23 on 2025-07-03 11:07

import app.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_pdfbook_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfbook',
            name='pdf_file',
            field=models.FileField(storage=app.storage.RawMediaCloudinaryStorage(), upload_to='pdfs/'),
        ),
    ]
