# Generated by Django 4.2.23 on 2025-07-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_pdfbook_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfbook',
            name='pdf_file',
            field=models.URLField(),
        ),
    ]
