# Generated by Django 4.2.23 on 2025-07-03 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_pdfbook_pdf_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downloadlog',
            options={'ordering': ['-timestamp']},
        ),
    ]
