# Generated by Django 4.2.23 on 2025-07-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_downloadlog_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfbook',
            name='author',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pdfbook',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
