# Generated by Django 4.2.23 on 2025-07-07 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
